import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// FIX (process-risk item, beta-launch audit 2026-07-05): the audit noted
// there was no automatic check that the hardcoded V7ContractBytecode string
// in x/humanity/keeper/contract_deploy.go actually matches a fresh compile
// of AequitasV7.sol — only a manual "Compiled from AequitasV7.sol on
// <date>" comment next to it, updated by hand. Every time the contract
// changes (like the P0-2 _confirmAlive UBI-forfeiture fix in this same
// audit pass), that string has to be regenerated by hand, and it's easy to
// forget under time pressure — the Go node would then deploy stale
// bytecode that doesn't match the reviewed/tested source at all, with
// nothing surfacing the mismatch.
//
// This test reads contract_deploy.go as text (same approach
// evm_v7_slots_source_test.go on the Go side uses to verify against the
// .sol source directly) and extracts the V7ContractBytecode string, then
// compares it against Hardhat's own freshly-compiled artifact for the same
// root AequitasV7.sol (via the contracts/ test fixture, whose own
// byte-identity to the root is guarded by AequitasV7_source_sync.ts).
describe("V7ContractBytecode (contract_deploy.go) stays in sync with a fresh compile", function () {
  it("matches Hardhat's freshly-compiled AequitasV7 creation bytecode", function () {
    const here = path.dirname(fileURLToPath(import.meta.url));

    const artifactPath = path.join(
      here,
      "..",
      "artifacts",
      "contracts",
      "AequitasV7.sol",
      "AequitasV7.json",
    );
    const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
    const freshBytecode: string = artifact.bytecode;
    assert.ok(
      freshBytecode && freshBytecode.startsWith("0x") && freshBytecode.length > 100,
      "Hardhat artifact bytecode looks empty or malformed — did the compile actually run before this test?",
    );
    const freshHex = freshBytecode.slice(2).toLowerCase();

    const goSourcePath = path.join(here, "..", "x", "humanity", "keeper", "contract_deploy.go");
    const goSource = readFileSync(goSourcePath, "utf8");
    const marker = 'const V7ContractBytecode = "';
    const start = goSource.indexOf(marker);
    assert.ok(start >= 0, `could not find ${marker} in contract_deploy.go — has the constant been renamed?`);
    const valueStart = start + marker.length;
    const valueEnd = goSource.indexOf('"', valueStart);
    assert.ok(valueEnd > valueStart, "could not find the closing quote for V7ContractBytecode");
    const goHex = goSource.slice(valueStart, valueEnd).toLowerCase();

    assert.equal(
      goHex,
      freshHex,
      "V7ContractBytecode in contract_deploy.go does not match a fresh compile of AequitasV7.sol. " +
        "If the contract source changed, regenerate the constant from " +
        "artifacts/contracts/AequitasV7.sol/AequitasV7.json's `bytecode` field " +
        "(strip the 0x prefix) — see this test file's own comment for why this matters.",
    );
  });
});
