"""Renders a list of per-ticker pipeline results into a markdown report."""

from datetime import date

from config import RISK_PROFILE

DISCLAIMER = (
    "_Generated by an AI multi-agent pipeline (technical, fundamental, "
    "sentiment analysts, each peer-reviewed by another agent with an "
    "unsupported-claims fact-check). Research output only — not executed as "
    "trades, not financial advice.\n"
    "Risk profile: **aggressive, bounded** — stop-loss/take-profit and "
    f"position size below are computed deterministically from ATR and the "
    f"profile's risk limits (max {RISK_PROFILE['max_position_pct']}% of capital "
    f"per position, {RISK_PROFILE['risk_per_trade_pct']}% risked per trade). "
    f"The {RISK_PROFILE['monthly_return_target_pct']}%/month figure is an "
    "**aspirational label only** — it is not a promise, not a backtest "
    "result, and nothing in this system guarantees it will be hit. No "
    "backtest has validated this strategy's real-world performance; treat "
    "every signal below as an unproven hypothesis, not a recommendation to "
    "trade._"
)


def _format_evidence(signal: dict) -> str:
    items = signal.get("evidence") or signal.get("sources") or []
    if not items:
        return ""
    return "\n".join(f"    - {item}" for item in items)


def render_markdown(results: list[dict], run_date: date) -> str:
    lines = [
        f"# Daily Trading Signals — {run_date.isoformat()}",
        "",
        DISCLAIMER,
        "",
    ]

    for result in results:
        ticker = result["ticker"]
        final = result["final"]
        rm = final.get("risk_management", {})

        lines += [
            f"## {ticker}: {final['final_direction'].upper()} "
            f"(confidence {final['final_confidence']:.2f})",
            "",
            final["summary"],
            "",
        ]

        if rm.get("position_size_pct"):
            lines += [
                f"**Risk-managed position:** entry ~{rm.get('entry_price')} | "
                f"stop-loss {rm.get('stop_loss_price')} | "
                f"take-profit {rm.get('take_profit_price')} | "
                f"size {rm.get('position_size_pct')}% of capital | "
                f"risk/reward {rm.get('risk_reward_ratio')}",
                "",
            ]
        elif rm:
            lines += [f"**Risk-managed position:** {rm.get('note', 'No position (hold).')}", ""]

        if final.get("dissenting_views"):
            lines.append("**Dissenting views:**")
            for view in final["dissenting_views"]:
                lines.append(f"- {view}")
            lines.append("")

        lines.append("<details><summary>Analyst signals & peer reviews (with fact-check)</summary>")
        lines.append("")
        for signal in result["signals"]:
            lines.append(
                f"- **{signal['agent']}**: {signal['direction']} "
                f"(confidence {signal['confidence']}) — {signal['reasoning']}"
            )
            evidence = _format_evidence(signal)
            if evidence:
                lines.append(evidence)
        lines.append("")
        for r in result["reviews"]:
            lines.append(
                f"- *{r['reviewer']}* reviewing *{r['target_agent']}*: "
                f"{r['agreement']} ({r['confidence_adjustment']:+}) — {r['critique']}"
            )
            unsupported = r.get("unsupported_claims") or []
            if unsupported:
                lines.append(f"    - ⚠️ Unsupported claims flagged: {unsupported}")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    return "\n".join(lines)
