"""Renders a list of per-ticker pipeline results into a markdown report."""

from datetime import date


def render_markdown(results: list[dict], run_date: date) -> str:
    lines = [
        f"# Daily Trading Signals — {run_date.isoformat()}",
        "",
        "_Generated by an AI multi-agent pipeline (technical, fundamental, "
        "sentiment analysts, each peer-reviewed by another agent). "
        "Research output only — not executed as trades, not financial advice._",
        "",
    ]

    for result in results:
        ticker = result["ticker"]
        final = result["final"]
        lines += [
            f"## {ticker}: {final['final_direction'].upper()} "
            f"(confidence {final['final_confidence']:.2f})",
            "",
            final["summary"],
            "",
        ]
        if final.get("dissenting_views"):
            lines.append("**Dissenting views:**")
            for view in final["dissenting_views"]:
                lines.append(f"- {view}")
            lines.append("")

        lines.append("<details><summary>Analyst signals & peer reviews</summary>")
        lines.append("")
        for signal in result["signals"]:
            lines.append(
                f"- **{signal['agent']}**: {signal['direction']} "
                f"(confidence {signal['confidence']}) — {signal['reasoning']}"
            )
        lines.append("")
        for r in result["reviews"]:
            lines.append(
                f"- *{r['reviewer']}* reviewing *{r['target_agent']}*: "
                f"{r['agreement']} ({r['confidence_adjustment']:+}) — {r['critique']}"
            )
        lines.append("")
        lines.append("</details>")
        lines.append("")

    return "\n".join(lines)
